name: Secret Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run TruffleHog secret scan
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        extra_args: '--max_depth 0 --json'  # Pass the args directly

    - name: Upload TruffleHog Report as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: trufflehog-report
        path: trufflehog_report.json

    - name: Check for secrets in the report
      run: |
        cat trufflehog_report.json
        if grep -q '\"Found\" : true' trufflehog_report.json; then
          echo "Secrets found!"
          exit 1
        else
          echo "No secrets found"
        fi
      continue-on-error: true
    
    - name: Print git Variables
      run: |
        echo "-------------------YRS-------------------"
        ls -lart
        pwd
        ls -lart ../
        ls -lart ../../
        echo "repository - ${{ github.repository }}"
        echo "REPO_NAME - ${{ github.event.repository.name }}"
        echo "head_ref - ${{ github.head_ref }}"
        echo "ref_name - ${{ github.ref_name }}"
        echo "event_name - ${{ github.event_name }}"
        echo "Below Variables are for PR - pull request:"
        echo "${{ github.event.pull_request.title }}"
        
