name: Secret Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Secret Scanning
      id: trufflehog
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./ # Path to scan
        extra_args:  --debug --results=verified,unknown # Optional arguments to pass to trufflehog
    
    - name: Scan Results Status 
      if: steps.trufflehog.outcome == 'failure' 
      run: exit 1

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: trufflehog-results
      continue-on-error: true
    
    - name: Print git Variables
      run: |
        echo "-------------------YRS-------------------"
        ls -lart
        pwd
        ls -lart ../
        ls -lart ../../
        echo "repository - ${{ github.repository }}"
        echo "REPO_NAME - ${{ github.event.repository.name }}"
        echo "head_ref - ${{ github.head_ref }}"
        echo "ref_name - ${{ github.ref_name }}"
        echo "event_name - ${{ github.event_name }}"
        echo "Below Variables are for PR - pull request:"
        echo "${{ github.event.pull_request.title }}"
        