name: Secret Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install TruffleHog
      run: |
        pip install trufflehog

    - name: Run TruffleHog Scan
      run: |
        trufflehog filesystem . --json > trufflehog_results.json

    - name: Upload TruffleHog results as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: trufflehog-results
        path: trufflehog_results.json

    - name: Fail on sensitive data found
      if: failure()
      run: |
        echo "TruffleHog found sensitive information in your repository!"
        exit 1
    
    - name: Print git Variables
      run: |
        echo "-------------------YRS-------------------"
        ls -lart
        pwd
        ls -lart ../
        ls -lart ../../
        echo "repository - ${{ github.repository }}"
        echo "REPO_NAME - ${{ github.event.repository.name }}"
        echo "head_ref - ${{ github.head_ref }}"
        echo "ref_name - ${{ github.ref_name }}"
        echo "event_name - ${{ github.event_name }}"
        echo "Below Variables are for PR - pull request:"
        echo "${{ github.event.pull_request.title }}"
        
